### ISSUE TITLE
Backup remains stuck in phase "Deleting", no additional delete requests honoured

### ISSUE THREAD

**Issue by rahulr3** [vmware-tanzu/velero-plugin-for-vsphere#345]
**Velero Version:**
Velero 1.5.4
Velero Plugin for AWS 1.1.0
Velero VSphere Plugin 1.1.0

Configured S3 storage using minio on a separate node.

Create a namespace with 150 PVs and 150 Pods with total 2400+ resources.
Create multiple backups (more than 30)

**Observations**
1. Deleted one of the backups, the backup remained in phase "Deleting" forever. This happened without Velero getting restarted.
2. Submitted additional requests for delete, but these were not picked by Velero for processing. The corresponding CR (deleteBackuprequests) showed status not updated.
3. Is this because Velero Delete Custom Controller remains blocked on earlier backup which remained in "Deleting" phase ?
4. Restarted Velero after which the subsequent delete requests were picked up for deletion. However, the first backup still remained in phase "Deleting".
5. Subsequent delete backup request was served and could delete the backup.
6. However, next backup was stuck again in phase "Deleting"
7. Additional delete requests were not picked up by velero.

**Comment by rahulr3** [comment]
[Uploading delete_issue_0428.zip…]()

Please find the attached logs as requested. All logs provided except esx + vc logs as the can't be accomodated within 10 MB limit imposed by GitHub.

**Comment by deepakkinni** [comment]
@rahulr3 
The logs attached not accessible, it's redirecting back to this issue. Please upload them again.

Anyways, based on the conversation in the email, I think I could point out a reason as to why the Backup delete may hang:

1. During the backup, a malformed Snapshot CRD is stored as the PVC annotation.
2. During the Backup delete we pick up this Snapshot CR from the PVC. This is used to extract the snapshot-id.
3. A DeleteSnapshot CRD is created with the extracted snapshot-id, velero at this point waits for the DeleteSnapshot CRD to either be completed successfully or fail.
4. ```Bug-1``` The backup driver fails while resolving the snapshot-id, but the failure doesn't put the DeleteSnapshot CR into a "Failed" state, which means the DeleteSnapshot CR is still in the "New" phase.
5. The backup driver continuously retries processing the DeleteSnapshot CR since it notices it's in "New" state, while velero is still waiting for the for DeleteSnapshot CR to either succeed or fail. This will cause the Backup delete to hang.

To confirm if this is what's happening I'd need to look at velero and backup driver logs for the velero Backup command to figure out what actually caused the malformed snapshot crd to be stored as pvc annotation.
Please upload them.

The other ```Bug-2``` noticed while triaging this issue is there is some error shadowing happening in snapshot manager, but this is unrelated to what issues you are noticing, I am mentioning it here for completeness sake.

**Comment by rahulr3** [comment]
[delete_issue_0428.zip](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/6399140/delete_issue_0428.zip)

**Comment by deepakkinni** [comment]
Thanks @rahulr3

m2bkp1

velero logs:

time="2021-04-30T00:42:32Z" level=info msg="Listing items" backup=velero/m2bkp1 group=v1 logSource="pkg/backup/item_collector.go:291" namespace=j2pv resource=pods
time="2021-04-30T00:42:32Z" level=info msg="Retrieved 2 items" backup=velero/m2bkp1 group=v1 logSource="pkg/backup/item_collector.go:297" namespace=j2pv resource=pods
time="2021-04-30T00:42:32Z" level=info msg="Getting items for resource" backup=velero/m2bkp1 group=v1 logSource="pkg/backup/item_collector.go:165" resource=persistentvolumeclaims
time="2021-04-30T00:42:32Z" level=info msg="Listing items" backup=velero/m2bkp1 group=v1 logSource="pkg/backup/item_collector.go:291" namespace=j2pv resource=persistentvolumeclaims
time="2021-04-30T00:42:32Z" level=info msg="Retrieved 2 items" backup=velero/m2bkp1 group=v1 logSource="pkg/backup/item_collector.go:297" namespace=j2pv resource=persistentvolumeclaims
.
.
time="2021-04-30T00:42:36Z" level=info msg="VSphere PVCBackupItemAction: StorageClass is not set for PVC j2pv/j2pvpod0pvc0" backup=velero/m2bkp1 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/backup_pvc_action_plugin.go:67" pluginName=velero-plugin-for-vsphere
.
.
time="2021-04-30T00:42:56Z" level=info msg="snapshot= snap-e8539258-358f-49ff-9001-4b2d2ca85414 changed, phase = Snapshotted" backup=velero/m2bkp1 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/snapshotUtils/snapshot.go:130" pluginName=velero-plugin-for-vsphere
time="2021-04-30T00:42:56Z" level=info msg="Persisting snapshot with snapshotID :pvc:j2pv/j2pvpod0pvc0:aXZkOmM4MmQwY2NmLTIwODItNGQ0NS04MmI5LTJjZWUwNWIzMTQ2ZTo1MjQ2ZWE3My1lNTA0LTRiMTgtOWRiNy1kMTNlNjcxZmE3NzI
.
.
time="2021-04-30T00:42:56Z" level=info msg="VSphere PVCBackupItemAction: StorageClass is not set for PVC j2pv/j2pvpod1pvc1" backup=velero/m2bkp1 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/backup_pvc_action_plugin.go:67" pluginName=velero-plugin-for-vsphere
.
.
time="2021-04-30T00:43:02Z" level=info msg="snapshot= snap-d03cfdd4-3460-4c81-941c-8c04907ef24c changed, phase = Snapshotted" backup=velero/m2bkp1 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/snapshotUtils/snapshot.go:130" pluginName=velero-plugin-for-vsphere
time="2021-04-30T00:43:02Z" level=info msg="Persisting snapshot with snapshotID :pvc:j2pv/j2pvpod1pvc1:aXZkOjgwNDRiZjNjLWU5ZGEtNDUyOC05OWFmLWM5ZTkzYTJmZWE0YTpjZmI0MDg5MC1mYTI5LTQ5MGItYWFkMy0xNWMzN2IwNWQzMWU


time="2021-04-30T00:43:03Z" level=info msg="Backup completed" controller=backup logSource="pkg/controller/backup_controller.go:642"


The backup starts at "2021-04-30T00:42:32Z", and ends at "2021-04-30T00:43:03Z", in this time frame there are 2 snapshots crated

`snapshot cr name:	snap-e8539258-358f-49ff-9001-4b2d2ca85414`
`pvc:				j2pv/j2pvpod0pvc0`
`fcd:				ivd:c82d0ccf-2082-4d45-82b9-2cee05b3146e:5246ea73-e504-4b18-9db7-d13e671fa772`

`snapshot cr name:	snap-d03cfdd4-3460-4c81-941c-8c04907ef24c`
`pvc:				j2pv/j2pvpod1pvc1`
`fcd:				ivd:8044bf3c-e9da-4528-99af-c9e93a2fea4a:cfb40890-fa29-490b-aad3-15c37b05d31e`

backup-driver logs:
time="2021-04-30T00:44:04Z" level=info msg="updateSnapshotStatusPhase: Snapshot j2pv/snap-e8539258-358f-49ff-9001-4b2d2ca85414 updated phase from Uploading to Uploaded" controller=BackupDriverController logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/backupdriver/backup_driver_controller.go:292"
.
.
time="2021-04-30T00:44:25Z" level=info msg="updateSnapshotStatusPhase: Snapshot j2pv/snap-d03cfdd4-3460-4c81-941c-8c04907ef24c updated phase from Uploading to Uploaded" controller=BackupDriverController logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/backupdriver/backup_driver_controller.go:292"


`At this point, we are certain that both the snapshots are uploaded to the remote repository.`

`A Backup delete for m2bkp1 was initiated at "2021-04-30T00:50:20Z" but I don't see the delete Backup request starting to be processed by velero, could the velero team take a look @zubron @nrb `

**Comment by ashish-amarnath** [comment]
All of Velero controllers reconcile only one object at a time.
So, when the backup delete request object is not being processed, is there a backup that is already being deleted?
Also, this may be unlikely, but if Velero is started in `--restore-only` mode, backup deletion requests are not processed. Is this flag passed to Velero server?

**Comment by deepakkinni** [comment]
I believe there is another backup delete in progress. From my understanding, one of the backup delete calls the plugin, but the plugin does not return(due to a bug described in my previous comment), do you think the plugin not returning could cause velero to hang on a single request? Is there a timeout for the plugin to process the delete?

**Comment by ashish-amarnath** [comment]
In the interest of better UX, Velero plugins should implement timeouts and cancellable operations in the plugin interface. In order to make backwards compatible changes to the plugin interface the issue of plugin versioning needs to be addressed. For velero V1.7 we are working on making a proposal for plugin versioning.

**Comment by ashish-amarnath** [comment]
The plugin not returning can definitely cause this. There is no timeout or cancellation in too the requests. That’s definitely something worth adding.

________________________________

**Comment by deepakkinni** [comment]
This issue should be mitigated by https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/351

**Comment by xing-yang** [comment]
This is fixed by #351, closing the bug.
